
all:
	cd f77 && $(MAKE)
	cd f95 && $(MAKE)
	cd f03 && $(MAKE)
	cd OpenMPTarget && $(MAKE)

clean:
	cd f77 && $(MAKE) clean
	cd f95 && $(MAKE) clean
	cd f03 && $(MAKE) clean
	cd OpenMPTarget && $(MAKE) clean
