
all:
	cd f77     && $(MAKE)
	cd f95     && $(MAKE)
	cd f03     && $(MAKE)
	cd failing && $(MAKE)

clean:
	cd f77     && $(MAKE) clean
	cd f95     && $(MAKE) clean
	cd f03     && $(MAKE) clean
	cd failing && $(MAKE) clean
