! Test: IMPORT dans les blocs d'interface
! Statements couverts: IMPORT (importe les entites du scope englobant
!                      dans un bloc d'interface)

MODULE IMPORTMOD
  IMPLICIT NONE

  INTEGER, PARAMETER :: WP = SELECTED_REAL_KIND(15)

  TYPE :: CONFIG
    INTEGER :: N
    REAL(WP) :: TOL
  END TYPE CONFIG

  ! IMPORT permet au bloc d'interface de voir CONFIG et WP
  INTERFACE
    SUBROUTINE SOLVER(CFG, X, IERR)
      IMPORT :: CONFIG, WP
      TYPE(CONFIG), INTENT(IN)  :: CFG
      REAL(WP),     INTENT(OUT) :: X(:)
      INTEGER,      INTENT(OUT) :: IERR
    END SUBROUTINE SOLVER

    FUNCTION OBJECTIVE(X) RESULT(F)
      IMPORT :: WP
      REAL(WP), INTENT(IN) :: X(:)
      REAL(WP) :: F
    END FUNCTION OBJECTIVE
  END INTERFACE

END MODULE IMPORTMOD


MODULE IMPL_MOD
  USE IMPORTMOD
  IMPLICIT NONE

CONTAINS

  SUBROUTINE SOLVER(CFG, X, IERR)
    TYPE(CONFIG), INTENT(IN)  :: CFG
    REAL(WP),     INTENT(OUT) :: X(:)
    INTEGER,      INTENT(OUT) :: IERR
    X    = 0.0_WP
    IERR = 0
    WRITE(*,*) 'SOLVER N=', CFG%N, ' TOL=', CFG%TOL
  END SUBROUTINE SOLVER

  FUNCTION OBJECTIVE(X) RESULT(F)
    REAL(WP), INTENT(IN) :: X(:)
    REAL(WP) :: F
    F = SUM(X**2)
  END FUNCTION OBJECTIVE

END MODULE IMPL_MOD


PROGRAM IMPORTTEST
  USE IMPORTMOD
  USE IMPL_MOD
  IMPLICIT NONE

  TYPE(CONFIG) :: CFG
  REAL(WP), ALLOCATABLE :: X(:)
  INTEGER :: IERR

  CFG = CONFIG(N=10, TOL=1.0E-8_WP)
  ALLOCATE(X(CFG%N))

  CALL SOLVER(CFG, X, IERR)
  WRITE(*,*) 'IERR =', IERR
  WRITE(*,*) 'OBJ =', OBJECTIVE(X)

  DEALLOCATE(X)
END PROGRAM IMPORTTEST
