! Test: nouvelles fonctions intrinseques F2003
! Statements couverts: MOVE_ALLOC, NEW_LINE, COMMAND_ARGUMENT_COUNT,
!                      GET_COMMAND_ARGUMENT, GET_COMMAND,
!                      GET_ENVIRONMENT_VARIABLE, IS_IOSTAT_END, IS_IOSTAT_EOR,
!                      SELECTED_CHAR_KIND, EXTENDS_TYPE_OF, SAME_TYPE_AS

PROGRAM INTRINSICF03
  USE ISO_FORTRAN_ENV
  IMPLICIT NONE

  ! MOVE_ALLOC
  REAL, ALLOCATABLE :: SRC(:), DST(:)
  INTEGER :: I, ARGC, ISTAT, VLEN, VSTATUS
  CHARACTER(LEN=200) :: CMD, ARG, ENVVAL
  LOGICAL :: EOR, EOF

  ALLOCATE(SRC(5))
  SRC = [(REAL(I), I=1,5)]
  CALL MOVE_ALLOC(FROM=SRC, TO=DST)
  WRITE(*,*) ALLOCATED(SRC), ALLOCATED(DST)
  WRITE(*,*) DST

  ! NEW_LINE
  WRITE(*,'(A)') 'LIGNE1' // NEW_LINE('A') // 'LIGNE2'

  ! COMMAND_ARGUMENT_COUNT
  ARGC = COMMAND_ARGUMENT_COUNT()
  WRITE(*,*) 'ARGC =', ARGC

  ! GET_COMMAND_ARGUMENT
  CALL GET_COMMAND_ARGUMENT(NUMBER=0, VALUE=ARG, STATUS=ISTAT)
  WRITE(*,*) 'PROGRAMME:', TRIM(ARG)

  DO I = 1, ARGC
    CALL GET_COMMAND_ARGUMENT(I, ARG)
    WRITE(*,*) 'ARG', I, ':', TRIM(ARG)
  END DO

  ! GET_COMMAND
  CALL GET_COMMAND(COMMAND=CMD, STATUS=ISTAT)
  WRITE(*,*) 'COMMANDE:', TRIM(CMD)

  ! GET_ENVIRONMENT_VARIABLE
  CALL GET_ENVIRONMENT_VARIABLE(NAME='HOME', VALUE=ENVVAL, &
                                LENGTH=VLEN, STATUS=VSTATUS)
  IF (VSTATUS == 0) WRITE(*,*) 'HOME=', TRIM(ENVVAL)

  CALL GET_ENVIRONMENT_VARIABLE('PATH', ENVVAL)
  WRITE(*,*) 'PATH (debut):', ENVVAL(1:40)

  ! IS_IOSTAT_END, IS_IOSTAT_EOR
  OPEN(NEWUNIT=I, STATUS='SCRATCH')
  WRITE(I,*) 1.0, 2.0
  REWIND(I)
  READ(I, *, IOSTAT=ISTAT) ENVVAL   ! provoque une erreur de conversion
  EOF = IS_IOSTAT_END(IOSTAT_END)
  EOR = IS_IOSTAT_EOR(IOSTAT_EOR)
  WRITE(*,*) 'IS_IOSTAT_END:', EOF
  WRITE(*,*) 'IS_IOSTAT_EOR:', EOR
  CLOSE(I)

  ! SELECTED_CHAR_KIND
  WRITE(*,*) SELECTED_CHAR_KIND('ASCII')
  WRITE(*,*) SELECTED_CHAR_KIND('DEFAULT')

  DEALLOCATE(DST)

END PROGRAM INTRINSICF03
