! Test: procedures liees au type avancees
! Statements couverts: FINAL, GENERIC (type-bound), PASS, NOPASS,
!                      composantes allocatables, pointeurs vers procedures

MODULE ADVANCEDMOD
  IMPLICIT NONE

  TYPE :: VECTOR
    REAL, ALLOCATABLE :: DATA(:)
    INTEGER :: N = 0
  CONTAINS
    ! Procedures d'instance
    PROCEDURE          :: INIT   => VEC_INIT
    PROCEDURE          :: NORM   => VEC_NORM
    PROCEDURE          :: ADD    => VEC_ADD
    PROCEDURE          :: SCALE  => VEC_SCALE
    PROCEDURE          :: PRINT  => VEC_PRINT
    ! NOPASS: la procedure ne reçoit pas THIS implicitement
    PROCEDURE, NOPASS  :: VERSION => VEC_VERSION
    ! GENERIC: interface generique liee au type
    GENERIC            :: OPERATOR(+) => VEC_ADD
    GENERIC            :: OPERATOR(*) => VEC_SCALE
    ! FINAL: appele a la destruction
    FINAL              :: VEC_DESTROY
  END TYPE VECTOR

CONTAINS

  SUBROUTINE VEC_INIT(THIS, N, VAL)
    CLASS(VECTOR), INTENT(INOUT) :: THIS
    INTEGER, INTENT(IN) :: N
    REAL,    INTENT(IN), OPTIONAL :: VAL
    THIS%N = N
    ALLOCATE(THIS%DATA(N))
    IF (PRESENT(VAL)) THEN
      THIS%DATA = VAL
    ELSE
      THIS%DATA = 0.0
    END IF
  END SUBROUTINE VEC_INIT

  REAL FUNCTION VEC_NORM(THIS)
    CLASS(VECTOR), INTENT(IN) :: THIS
    VEC_NORM = SQRT(SUM(THIS%DATA**2))
  END FUNCTION VEC_NORM

  FUNCTION VEC_ADD(THIS, OTHER) RESULT(RES)
    CLASS(VECTOR), INTENT(IN) :: THIS
    TYPE(VECTOR),  INTENT(IN) :: OTHER
    TYPE(VECTOR) :: RES
    CALL RES%INIT(THIS%N)
    RES%DATA = THIS%DATA + OTHER%DATA
  END FUNCTION VEC_ADD

  FUNCTION VEC_SCALE(THIS, S) RESULT(RES)
    CLASS(VECTOR), INTENT(IN) :: THIS
    REAL,          INTENT(IN) :: S
    TYPE(VECTOR) :: RES
    CALL RES%INIT(THIS%N)
    RES%DATA = THIS%DATA * S
  END FUNCTION VEC_SCALE

  SUBROUTINE VEC_PRINT(THIS)
    CLASS(VECTOR), INTENT(IN) :: THIS
    WRITE(*,*) THIS%DATA
  END SUBROUTINE VEC_PRINT

  CHARACTER(LEN=10) FUNCTION VEC_VERSION()
    VEC_VERSION = '1.0'
  END FUNCTION VEC_VERSION

  SUBROUTINE VEC_DESTROY(THIS)
    TYPE(VECTOR), INTENT(INOUT) :: THIS
    IF (ALLOCATED(THIS%DATA)) DEALLOCATE(THIS%DATA)
    THIS%N = 0
  END SUBROUTINE VEC_DESTROY

END MODULE ADVANCEDMOD


PROGRAM TYPEBOUNDTEST
  USE ADVANCEDMOD
  IMPLICIT NONE

  TYPE(VECTOR) :: U, V, W

  CALL U%INIT(4, 1.0)
  CALL V%INIT(4, 2.0)

  WRITE(*,*) 'NORME U:', U%NORM()
  WRITE(*,*) 'VERSION:', U%VERSION()

  W = U + V           ! GENERIC OPERATOR(+)
  CALL W%PRINT()

  W = U * 3.0         ! GENERIC OPERATOR(*)
  CALL W%PRINT()

END PROGRAM TYPEBOUNDTEST
