! Test: heritage de type et polymorphisme
! Statements couverts: TYPE EXTENDS, CLASS, SELECT TYPE / TYPE IS / CLASS IS / END SELECT,
!                      procedures liees au type (type-bound procedures)

MODULE SHAPESMOD
  IMPLICIT NONE

  ! Type de base
  TYPE :: SHAPE
    REAL :: COLOR(3) = [0.0, 0.0, 0.0]
  CONTAINS
    PROCEDURE :: AREA  => SHAPE_AREA
    PROCEDURE :: PRINT => SHAPE_PRINT
  END TYPE SHAPE

  ! Extension: CIRCLE herite de SHAPE
  TYPE, EXTENDS(SHAPE) :: CIRCLE
    REAL :: RADIUS
  CONTAINS
    PROCEDURE :: AREA => CIRCLE_AREA
  END TYPE CIRCLE

  ! Extension: RECTANGLE herite de SHAPE
  TYPE, EXTENDS(SHAPE) :: RECTANGLE
    REAL :: WIDTH, HEIGHT
  CONTAINS
    PROCEDURE :: AREA => RECT_AREA
  END TYPE RECTANGLE

  ! Double heritage: SPHERE herite de CIRCLE
  TYPE, EXTENDS(CIRCLE) :: SPHERE
  CONTAINS
    PROCEDURE :: AREA => SPHERE_AREA
  END TYPE SPHERE

CONTAINS

  REAL FUNCTION SHAPE_AREA(THIS)
    CLASS(SHAPE), INTENT(IN) :: THIS
    SHAPE_AREA = 0.0
  END FUNCTION SHAPE_AREA

  SUBROUTINE SHAPE_PRINT(THIS)
    CLASS(SHAPE), INTENT(IN) :: THIS
    WRITE(*,*) 'SHAPE, AREA =', THIS%AREA()
  END SUBROUTINE SHAPE_PRINT

  REAL FUNCTION CIRCLE_AREA(THIS)
    CLASS(CIRCLE), INTENT(IN) :: THIS
    CIRCLE_AREA = 3.14159265 * THIS%RADIUS**2
  END FUNCTION CIRCLE_AREA

  REAL FUNCTION RECT_AREA(THIS)
    CLASS(RECTANGLE), INTENT(IN) :: THIS
    RECT_AREA = THIS%WIDTH * THIS%HEIGHT
  END FUNCTION RECT_AREA

  REAL FUNCTION SPHERE_AREA(THIS)
    CLASS(SPHERE), INTENT(IN) :: THIS
    SPHERE_AREA = 4.0 * 3.14159265 * THIS%RADIUS**2
  END FUNCTION SPHERE_AREA

  ! Procedure polymorphe: prend n'importe quelle SHAPE
  SUBROUTINE DESCRIBE(S)
    CLASS(SHAPE), INTENT(IN) :: S

    ! SELECT TYPE: dispatch selon le type dynamique
    SELECT TYPE (S)
      TYPE IS (CIRCLE)
        WRITE(*,*) 'CIRCLE, R =', S%RADIUS
      TYPE IS (RECTANGLE)
        WRITE(*,*) 'RECTANGLE', S%WIDTH, 'x', S%HEIGHT
      CLASS IS (SPHERE)
        WRITE(*,*) 'SPHERE ou sous-type'
      CLASS DEFAULT
        WRITE(*,*) 'SHAPE generique'
    END SELECT
  END SUBROUTINE DESCRIBE

END MODULE SHAPESMOD


PROGRAM OOPTEST
  USE SHAPESMOD
  IMPLICIT NONE

  TYPE(CIRCLE)    :: C
  TYPE(RECTANGLE) :: R
  TYPE(SPHERE)    :: SP
  CLASS(SHAPE), ALLOCATABLE :: S

  C  = CIRCLE(RADIUS=2.0)
  R  = RECTANGLE(WIDTH=3.0, HEIGHT=4.0)
  SP = SPHERE(RADIUS=1.0)

  ! Appels de procedures liees au type
  WRITE(*,*) C%AREA()
  WRITE(*,*) R%AREA()
  CALL C%PRINT()

  ! Polymorphisme via CLASS
  CALL DESCRIBE(C)
  CALL DESCRIBE(R)
  CALL DESCRIBE(SP)

  ! Allocation polymorphe
  ALLOCATE(CIRCLE :: S)
  SELECT TYPE (S)
    TYPE IS (CIRCLE)
      S%RADIUS = 5.0
  END SELECT
  WRITE(*,*) S%AREA()
  DEALLOCATE(S)

END PROGRAM OOPTEST
