! Test: ISO_FORTRAN_ENV et IEEE_ARITHMETIC
! Statements couverts: USE ISO_FORTRAN_ENV, constantes de l'environnement,
!                      unites standard INPUT_UNIT, OUTPUT_UNIT, ERROR_UNIT

PROGRAM ISOENVTEST
  USE ISO_FORTRAN_ENV
  IMPLICIT NONE

  INTEGER :: I
  REAL    :: R
  REAL(REAL32)  :: R32
  REAL(REAL64)  :: R64
  REAL(REAL128) :: R128
  INTEGER(INT8)  :: I8
  INTEGER(INT16) :: I16
  INTEGER(INT32) :: I32
  INTEGER(INT64) :: I64

  ! Constantes de ISO_FORTRAN_ENV
  WRITE(*,*) 'FORTRAN VERSION:', COMPILER_VERSION()
  WRITE(*,*) 'COMPILER OPTIONS:', COMPILER_OPTIONS()

  ! Unites d'I/O standard
  WRITE(OUTPUT_UNIT, *) 'VERS STDOUT'
  WRITE(ERROR_UNIT,  *) 'VERS STDERR'

  ! Tailles des types
  WRITE(*,*) 'NUMERIC_STORAGE_SIZE:', NUMERIC_STORAGE_SIZE
  WRITE(*,*) 'CHARACTER_STORAGE_SIZE:', CHARACTER_STORAGE_SIZE
  WRITE(*,*) 'FILE_STORAGE_SIZE:', FILE_STORAGE_SIZE

  ! Kinds garantis
  WRITE(*,*) 'REAL32 KIND:', REAL32
  WRITE(*,*) 'REAL64 KIND:', REAL64
  WRITE(*,*) 'INT32 KIND:', INT32
  WRITE(*,*) 'INT64 KIND:', INT64

  ! Utilisation des types a precision garantie
  R32  = 3.14_REAL32
  R64  = 3.14159265358979_REAL64
  R128 = 3.14159265358979323846_REAL128
  I8   = 127_INT8
  I16  = 32767_INT16
  I32  = 2147483647_INT32
  I64  = 9223372036854775807_INT64

  WRITE(*,*) R32, R64
  WRITE(*,*) I8, I16, I32, I64

  ! Tableaux des kinds disponibles
  WRITE(*,*) 'INTEGER KINDS:', INTEGER_KINDS
  WRITE(*,*) 'REAL KINDS:', REAL_KINDS
  WRITE(*,*) 'LOGICAL KINDS:', LOGICAL_KINDS
  WRITE(*,*) 'CHARACTER KINDS:', CHARACTER_KINDS

  ! IOSTAT predefinies
  WRITE(*,*) 'IOSTAT_END:', IOSTAT_END
  WRITE(*,*) 'IOSTAT_EOR:', IOSTAT_EOR

END PROGRAM ISOENVTEST
