! Test: MODULE / END MODULE / USE / CONTAINS / PUBLIC / PRIVATE
! Statements couverts: MODULE, END MODULE, USE, USE...ONLY, USE...renaming,
!                      PUBLIC, PRIVATE, CONTAINS

MODULE MATHMOD
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: PI, TWOPI, SQUARE, ADD

  REAL, PARAMETER :: PI    = 3.14159265358979
  REAL, PARAMETER :: TWOPI = 2.0 * PI

CONTAINS

  REAL FUNCTION SQUARE(X)
    REAL, INTENT(IN) :: X
    SQUARE = X * X
  END FUNCTION SQUARE

  REAL FUNCTION ADD(A, B)
    REAL, INTENT(IN) :: A, B
    ADD = A + B
  END FUNCTION ADD

END MODULE MATHMOD


MODULE STRMOD
  IMPLICIT NONE
  PUBLIC

  CHARACTER(LEN=20) :: DEFAULT_MSG = 'HELLO'

CONTAINS

  SUBROUTINE GREET(MSG)
    CHARACTER(LEN=*), INTENT(IN) :: MSG
    WRITE(*,*) TRIM(MSG)
  END SUBROUTINE GREET

END MODULE STRMOD


PROGRAM MODTEST
  ! USE sans restriction
  USE MATHMOD
  ! USE avec ONLY
  USE STRMOD, ONLY : GREET
  ! USE avec renommage
  USE MATHMOD, MYPI => PI

  IMPLICIT NONE
  REAL :: X, Y

  X = SQUARE(3.0)
  Y = ADD(1.0, 2.0)
  WRITE(*,*) PI, TWOPI, MYPI
  CALL GREET('BONJOUR')
END PROGRAM MODTEST
